### PR TITLE
Use pre-commit on features directory

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Execute pre-commit hooks on features folder.

Pre-commit (https://pre-commit.com/) is an opinionated formatter that can enable several plugins. This for example pre-validates that:

- yamls conform to standard
- xml have no parse errors
- markdown recommendations are respected (spaces before and after titles, etc)
- Files have executable shebang if marked executable
- End of file fixer
- etc

This commit, addresses all pre-commit concerns on this folder in the  repository

Fixes # (issue)

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by iranzo** [comment]
[test-ipi]

**Comment by iranzo** [comment]
[test-ipi]

**Comment by rlopez133** [comment]
@slintes @MarSik -- what are your thoughts on merging this into your features dir?

**Comment by slintes** [comment]
Since this is not under active development anymore, I would prefer to not touch it at all. Tbh I find it a bit risky to modify scripts etc.
And please do not touch the vendor directory for sure.

**Pull request closed without merging**
