### PR TITLE
Validate and wrap IP addresses

### PR DESCRIPTION
**Pull request by yprokule**
# Description

Validate if specified address is valid IP address and if it's IPv6 address wrap it in square `[` `]` brackets.

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Run playbook

**Test Configuration**:

- Versions: 4.3
- Hardware: virtual

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [x] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by rlopez133** [comment]
Does the ipwrap also work for ipv4?

**Comment by rlopez133** [comment]
@yprokule so this requires the package netaddr on the control machine. Let me figure out some logic here to make sure that requirement is met before I add this.

**Comment by yprokule** [comment]
> @yprokule so this requires the package netaddr on the control machine. Let me figure out some logic here to make sure that requirement is met before I add this.

sure @rlopez133

**Comment by rlopez133** [comment]
[test-ipi]

**Pull request merged**
