### PR TITLE
Use fail for checking ansible version

### LINKED ISSUE #333: Playbook errors with a incorrect error when ansible is <2.9
When using ansible 2.8, the playbook exits with a language error when it should exit with a wrong version error. 

*** With ansible 2.8

TASK [node-prep : include_tasks] **********************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:14:58 -0400 (0:00:01.483)       0:00:01.536 *********
fatal: [provision.osp.example.com]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to be in '/home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Python libraries are installed\n  ^ here\n"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
provision.osp.example.com  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0              

*** With ansible 2.9

TASK [node-prep : include_tasks] **********************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:02.595)       0:00:02.631 *********
included: /home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml for provision.osp.example.com                                                                                    

TASK [node-prep : Check ansible version] **************************************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:00.194)       0:00:02.826 *********
ok: [provision.osp.example.com -> localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [node-prep : Ensure Python libraries are installed] **********************************************************************************************************************************************************
Tuesday 28 April 2020  15:22:11 -0400 (0:00:00.056)       0:00:02.882 *********
ok: [provision.osp.example.com -> localhost]

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Uses 'fail' module to fail installation if ansible version is not minimum required

Closes #333 

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by colonwq** [comment]
Don't we want to fail when the version is < 2.9.0?

"when: ansible_version.full is version('2.9.0', '<')"

**Comment by iranzo** [comment]
[test-ipi]

**Pull request merged**
