### PR TITLE
Reorder Troubleshooting with new data in IPv6 PR

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Reorganize troubleshooting with new data from IPv6 PR

Fixes # (issue)

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by rlopez133** [comment]
nothing wrong with the PR per se, but I think we need to clean up the Failed Ignition during Firstboot as the flow doesn't match. In the sense its not part of the workflow we have (diagrams). Maybe it should be? Maybe its better to have as part of Misc?

**Comment by iranzo** [comment]
Moved in latest push:

imagen


https://deploy-preview-420--baremetal-deploy.netlify.app/4.5/troubleshooting

@rlopez133 what about like this?

**Comment by rlopez133** [comment]
> Moved in latest push:
> 
> imagen
> 
> https://deploy-preview-420--baremetal-deploy.netlify.app/4.5/troubleshooting
> 
> @rlopez133 what about like this?

@iranzo this works for me right now. We can always reassess later. 

/lgtm

**Pull request merged**
