### PR TITLE
Proper python-netaddr package

### LINKED ISSUE #227: ansible playbooks doesn't work in CentOS7 due to python2-netaddr doesn't exist
The `python2-netaddr` package doesn't exist in CentOS7, it is `python-netaddr` so as #225 has been merged, the provision fails.

### PR DESCRIPTION
**Pull request by e-minguez**
# Description

Fixes #227 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Tested in my baremetal environment

**Test Configuration**:

- Versions: ocp4 latest
- Hardware: bare metal

## Checklist

- [x] I have performed a self-review of my own code
- [x] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [x] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [x] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [x] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by e-minguez** [comment]
As mentioned https://github.com/openshift-kni/baremetal-deploy/issues/227#issuecomment-600481463 it seems there are better ways to verify the python modules installed, but meanwhile this will fix it.

**Comment by rlopez133** [comment]
this isnt going to work bc it doesnt apply to rhel8 nor fedora . Both of these don't have a python-dns package

**Comment by e-minguez** [comment]
> this isnt going to work bc it doesnt apply to rhel8 nor fedora . Both of these don't have a python-dns package

This temporary fix is for python-netaddr, no python2-dns. But in any case, this can be merged temporary as there are better ways to validate the python modules (and no distro dependant)

**Comment by rlopez133** [comment]
> > this isnt going to work bc it doesnt apply to rhel8 nor fedora . Both of these don't have a python-dns package
> 
> This temporary fix is for python-netaddr, no python2-dns. But in any case, this can be merged temporary as there are better ways to validate the python modules (and no distro dependant)

check out #229  and see if that fixes what you need. If it does , I'll merge that in

**Pull request closed without merging**
