### PR TITLE
Hide pullsecret in ansible verbose mode

### PR DESCRIPTION
**Pull request by fdaencarrh**
# Description

Hide pullsecret in ansible verbose mode.

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [x] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by DirectedSoul1** [comment]
Hi @fdaencarrh thanks for raising this PR, I'm curious to understand the use case of this PR, is it only applicable while running only disconnected installs?

**Comment by fdaencarrh** [comment]
> Hi @fdaencarrh thanks for raising this PR, I'm curious to understand the use case of this PR, is it only applicable while running only disconnected installs?

Hi @DirectedSoul1, exactly. I was doing a screen-cast for demo purpose and i saw these secrets appear. It will be great if we can hide them.

**Comment by iranzo** [comment]
[test-ipi]

**Comment by iranzo** [comment]
check dallas ocp-4.6-vanilla

**Comment by iranzo** [comment]
Thanks for your contribution @fdaencarrh !

**Comment by sreichar** [comment]
@iranzo asked me to manually merge wiht CI system down

**Comment by fdaencarrh** [comment]
Thanks for the quick review !

**Pull request merged**
