### PR TITLE
Update Podman library to use collection

### LINKED ISSUE #679: Update podman ansible module
I've just deployed a fresh rhel8 and provisioning openshift using these playbooks fails when creating the container registry container:

```
TASK [installer : Create container to serve the registry] **********************
Tuesday 02 March 2021  15:43:06 +0000 (0:00:00.927)       0:01:33.484 ********* 

fatal: [kni1-bootstrap.cloud.lab.eng.bos.redhat.com -> kni1-bootstrap.cloud.lab.eng.bos.redhat.com]: FAILED! => {"changed": false, "msg": "Can't create container ocpdiscon-registry", "stderr": "Error: unknown flag: --detach\n", "stderr_lines": ["Error: unknown flag: --detach"], "stdout": "", "stdout_lines": []}
```

It seems it uses the podman_container library https://github.com/openshift-kni/baremetal-deploy/blob/4d266ad25461cd1099bd47498f10db665c59a32d/ansible-ipi-install/roles/installer/library/podman_container.py#L11 but it seems a little bit outdated (https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_containers.py)

Just in case, my podman version is 2.2.1 from a just updated RHEL8 box.

Thanks.

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Replaces podman library by collection

Fixes #679 

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by iranzo** [comment]
[test-ipi]

**Comment by iranzo** [comment]
check dallas ocp-4.6-vanilla

**Comment by iranzo** [comment]
image

**Comment by DirectedSoul1** [comment]
Tested PR on my `kni3` environment and results are here 

```
[kni@kni3-deployhost ~]$ oc get co
NAME                                       VERSION                             AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.8.0-0.nightly-2021-03-30-160509   True        False         False      101m
baremetal                                  4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
cloud-credential                           4.8.0-0.nightly-2021-03-30-160509   True        False         False      160m
cluster-autoscaler                         4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
config-operator                            4.8.0-0.nightly-2021-03-30-160509   True        False         False      125m
console                                    4.8.0-0.nightly-2021-03-30-160509   False       True          False      117m
csi-snapshot-controller                    4.8.0-0.nightly-2021-03-30-160509   True        False         False      111m
dns                                        4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
etcd                                       4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
image-registry                             4.8.0-0.nightly-2021-03-30-160509   True        False         False      118m
ingress                                    4.8.0-0.nightly-2021-03-30-160509   True        False         True       118m
insights                                   4.8.0-0.nightly-2021-03-30-160509   True        False         False      118m
kube-apiserver                             4.8.0-0.nightly-2021-03-30-160509   True        False         False      121m
kube-controller-manager                    4.8.0-0.nightly-2021-03-30-160509   True        False         False      121m
kube-scheduler                             4.8.0-0.nightly-2021-03-30-160509   True        False         False      122m
kube-storage-version-migrator              4.8.0-0.nightly-2021-03-30-160509   True        False         False      121m
machine-api                                4.8.0-0.nightly-2021-03-30-160509   True        False         False      120m
machine-approver                           4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
machine-config                             4.8.0-0.nightly-2021-03-30-160509   True        False         False      122m
marketplace                                4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
monitoring                                 4.8.0-0.nightly-2021-03-30-160509   True        False         False      10m
network                                    4.8.0-0.nightly-2021-03-30-160509   True        False         False      124m
node-tuning                                4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
openshift-apiserver                        4.8.0-0.nightly-2021-03-30-160509   True        False         False      114m
openshift-controller-manager               4.8.0-0.nightly-2021-03-30-160509   True        False         False      122m
openshift-samples                          4.8.0-0.nightly-2021-03-30-160509   True        False         False      118m
operator-lifecycle-manager                 4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
operator-lifecycle-manager-catalog         4.8.0-0.nightly-2021-03-30-160509   True        False         False      123m
operator-lifecycle-manager-packageserver   4.8.0-0.nightly-2021-03-30-160509   True        False         False      120m
service-ca                                 4.8.0-0.nightly-2021-03-30-160509   True        False         False      124m
storage                                    4.8.0-0.nightly-2021-03-30-160509   True        False         False      125m
[kni@kni3-deployhost ~]$ oc get nodes
NAME                                              STATUS   ROLES           AGE    VERSION
kni3-master-0.kni3.cloud.lab.eng.bos.redhat.com   Ready    master,worker   128m   v1.20.0+29a606d
kni3-master-1.kni3.cloud.lab.eng.bos.redhat.com   Ready    master,worker   130m   v1.20.0+29a606d
kni3-master-2.kni3.cloud.lab.eng.bos.redhat.com   Ready    master,worker   129m   v1.20.0+29a606d

```

**Review by DirectedSoul1 — COMMENTED** [review]
"tested on my `kni3` environment" 
/approve

**Pull request merged**
