### PR TITLE
Add option to define cluster_pro_if

### PR DESCRIPTION
**Pull request by johnbieren**
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

# Description

In the virt environment, we are using a different interface in the metal3-config than prov_nic. Allow this to be configured

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Ran locally

**Test Configuration**:

- Versions: rhel 8.1
- Hardware: virt

## Checklist

- [X] I have performed a self-review of my own code
- [X] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by rlopez133** [comment]
hey @johnbieren I'm going to let others chime in, but in my opinion, this is very specific to your environment and not sure its a use case that needs to be captured by the playbook? I'm wondering if a better workaround for your envs would be to just modify the roles/installer/templates/metal3-config.j2 with the specific nic that you need.

**Comment by rlopez133** [comment]
cc @abays and @e-minguez for their 2 cents above

**Comment by yprokule** [comment]
> hey @johnbieren I'm going to let others chime in, but in my opinion, this is very specific to your environment and not sure its a use case that needs to be captured by the playbook? I'm wondering if a better workaround for your envs would be to just modify the roles/installer/templates/metal3-config.j2 with the specific nic that you need.

@rlopez133 imho, this makes playbook more easily adoptable by others, despite environment being used

**Comment by abays** [comment]
> > hey @johnbieren I'm going to let others chime in, but in my opinion, this is very specific to your environment and not sure its a use case that needs to be captured by the playbook? I'm wondering if a better workaround for your envs would be to just modify the roles/installer/templates/metal3-config.j2 with the specific nic that you need.
> 
> @rlopez133 imho, this makes playbook more easily adoptable by others, despite environment being used

This actually brings up a larger concern.  Namely, that there might not be parity between the provisioning host interface names (both provisioning and baremetal) and the cluster nodes' interface names.  I don't think it matters for `pub_nic`, as that doesn't seem to be used for anything other than the provisioning host, but it indeed would be a potential concern for `prov_nic`, because we use it for both configuring the provisioning host and for setting cluster `install-config.yaml` and `metal3-config.yaml`.

**Comment by rlopez133** [comment]
> > > hey @johnbieren I'm going to let others chime in, but in my opinion, this is very specific to your environment and not sure its a use case that needs to be captured by the playbook? I'm wondering if a better workaround for your envs would be to just modify the roles/installer/templates/metal3-config.j2 with the specific nic that you need.
> > 
> > 
> > @rlopez133 imho, this makes playbook more easily adoptable by others, despite environment being used
> 
> This actually brings up a larger concern. Namely, that there might not be parity between the provisioning host interface names (both provisioning and baremetal) and the cluster nodes' interface names. I don't think it matters for `pub_nic`, as that doesn't seem to be used for anything other than the provisioning host, but it indeed would be a potential concern for `prov_nic`, because we use it for both configuring the provisioning host and for setting cluster `install-config.yaml` and `metal3-config.yaml`.

To add, @yprokule @abays @johnbieren the goal is to keep the playbook as close to best practice and what is reflected in the documentation. Not to mention, adding these corner cases also makes it more difficult to troubleshoot as we may not have an environment that can test it.

**Comment by rlopez133** [comment]
@yprokule @abays @johnbieren - I'm going to close this PR since the goal is to stay as close as possible to best practices and the install-steps.md

**Pull request closed without merging**
