### PR TITLE
Use triple quotes

### LINKED ISSUE #509: Documentation issue: The nmcli command fails due to environment variables
I found a trivial error and will report it.

Occurs in RHEL 8.2, issue for: [ipi-install-nmcli-setup.adoc](https://github.com/openshift-kni/baremetal-deploy/blob/master/documentation/ipi-install/modules/ipi-install-nmcli-setup.adoc)

Environment variables exported by the `kni` user are not passed to commands with `sudo bash -c`.

```
[kni@provisioner ~]$ export HOGE=hoge
[kni@provisioner ~]$ echo $HOGE is not emply
hoge is not emply
[kni@provisioner ~]$ sudo bash -c 'echo $HOGE is empty'
is empty
```

As a result, the connection is neither down nor deleted and still remains after the command, and an error is recorded in `nohup.out`.

```
$ sudo cat nohup.out
Error: '' is not an active connection.
Error: no active connection provided.
Error: unknown connection ''.
Error: cannot delete unknown connection(s): ''.
Error: 'System ' is not an active connection.
Error: no active connection provided.
Error: unknown connection 'System '.
Error: cannot delete unknown connection(s): 'System '.
Connection 'baremetal' (f57800ad-10c8-4868-9a26-d2d2d88eda63) successfully added.
Connection 'bridge-slave' (f57800ad-10c8-4868-9a26-d2d2d88eda63) successfully added.
Connection 'baremetal' successfully deactivated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/4)
```

I had to fix those connections manually after the procedure was performed.
The same issue happens with the command for provision network.

The easiest way is to add the `-E` option to `sudo` like `sudo -E nohup bash -c 'some commands'`.

```
[kni@provisioner ~]$ sudo -E bash -c 'echo $HOGE is not empty'
hoge is not empty
```

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Use triple quotes in code sent to sudo

Fixes #509 

## Type of change

Please select the appropiate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by kurokobo** [comment]
In `modules/ipi-install-nmcli-setup.adoc`, the lines 15 and 24-25 should be fixed too.

Thank you for your work for the issue!
I'm not an approved reviewer, so I just leave a comment. Thanks.

**Comment by iranzo** [comment]
> In `modules/ipi-install-nmcli-setup.adoc`, the lines 15 and 24-25 should be fixed too.
> 
> Thank you for your work for the issue!
> I'm not an approved reviewer, so I just leave a comment. Thanks.

Thanks, I was modifying them on the 4.3 release and missed the ones on top. It's uploaded already

**Comment by kurokobo** [comment]
Sorry to keep bothering you, but we can simply replace single quote with double quote instead of triple double-quote.
Seems that the triple quote has no special meaning in Bash. I was confused with python, sorry.

```bash
[kni@provisioner ~]$ export HOGE=hoge
[kni@provisioner ~]$ export FUGA=fuga
[kni@provisioner ~]$ sudo nohup bash -c "
> echo "$HOGE" is hoge
> echo "$FUGA" is fuga
> "
nohup: ignoring input and appending output to 'nohup.out'

[kni@provisioner ~]$ sudo cat nohup.out 
hoge is hoge
fuga is fuga
```

**Comment by iranzo** [comment]
> ```shell
>  sudo nohup bash -c "
> > echo "$HOGE" is hoge
> > echo "$FUGA" is fuga
> > "
> ```

For me works fine on both RHEL 8.2 and Fedora 32:
image

**Comment by iranzo** [comment]
@kurokobo it was merged with triple quotes, does it work for you with them as it does for me? or do you want me to submit another PR?

Thanks!

**Comment by kurokobo** [comment]
@iranzo 
Thanks, yes the triple quote works for me too.
What I care about is that triple quote has no special meaning, therefore `"""hoge"""` is no different than simply concatenating `""`(empty string), `"hoge"`, and `""`.
We can make the code more simple with single double-quote, but it's ok to close, it works anyway. Thanks!

**Pull request merged**
