### PR TITLE
Increase provisioning network size

### PR DESCRIPTION
**Pull request by smalleni**
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

# Description
This increases the default provisioning network size.
Fixes # (issue)

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by DirectedSoul1** [comment]
Hi @smalleni , thanks for opening this new PR and also closing the PR #556 , I was just curious to know the use case here, `172.22.0.2/24` still allows the possible 250+ systems under the subnet, is there a specific use case that we are looking for under `/21` subnet?

**Comment by DirectedSoul1** [comment]
Hi @smalleni , thanks for opening this new PR and also closing the PR #556 , I was just curious to know the use case here, `172.22.0.2/24` still allows the possible 250+ systems under the subnet, is there a specific use case that we are looking for under `/21` subnet?

**Comment by smalleni** [comment]
> Hi @smalleni , thanks for opening this new PR and also closing the PR #556 , I was just curious to know the use case here, `172.22.0.2/24` still allows the possible 250+ systems under the subnet, is there a specific use case that we are looking for under `/21` subnet?

@DirectedSoul1 I'm deploying 500+ baremetal nodes in the scale lab :) Had a conversation with @rlopez133 to bump the default instead of making it configurable (which adds yet another var)

**Pull request merged**
