### PR TITLE
Added IPv6 information

### PR DESCRIPTION
**Pull request by mvazquezc**
# Description

This PR includes some documentation around IPv6 disconnected environments. 

## Type of change

Please select the appropriate options:

- [X ] New feature (non-breaking change which adds functionality)
- [X ] This change requires a documentation update

## Testing

This information is based on the documentation we have to deploy fully disconnected IPv6 clusters internally. 

**Test Configuration**:

- Versions: OCP 4.4+
- Hardware: Baremetal

## Checklist

- [ X ] I have performed a self-review of my own code
- [ X ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by rlopez133** [comment]
hey @mvazquezc , FYI upcoming install-steps is going to be a pointer to multiple different documents. The current install-steps.md will become 4.3 , while new 4.4 doc will be created as well as a disconnected doc. All the docs will be work forumlated between our group and the docs team so that there is consistency upstream and downstream. Once I get a copy of the disconnected doc from the docs team, I'll share that PR but it should have a lot of what you have in here already since you shared with them your doc previously.

**Comment by mvazquezc** [comment]
@rlopez133 Nice, I can review that PR when it's ready then. Thanks!

**Comment by rlopez133** [comment]
@mvazquezc wondering if there has been any progress making these pieces modules to include somewhere in: https://openshift-kni.github.io/baremetal-deploy/

**Comment by mvazquezc** [comment]
> @mvazquezc wondering if there has been any progress making these pieces modules to include somewhere in: https://openshift-kni.github.io/baremetal-deploy/

Hey @rlopez133, I will start working on that this week.

**Comment by iranzo** [comment]
Closing this one as it has been added in a new PR #415

**Pull request closed without merging**
