### PR TITLE
Lower down manifest number

### LINKED ISSUE #404: Rename 99_ manifests to 98_ as workaround for MCO bug
There's an ordering issue in MCO when using any custom manifests with
the 99_ prefix. Custom manifest until this is fixed should all start
with 98_ (or some lower number).

Bug here: https://github.com/openshift-metal3/dev-scripts/pull/1039

We need to fix our script to not create with 99_ prefix but use 98_ instead.

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Rename manifests with 99- or 99_ to 98 to avoid bug https://github.com/openshift-metal3/dev-scripts/pull/1039

Fixes # (issue)

Closes #404

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [x] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [x] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by iranzo** [comment]
[test-ipi]

**Comment by iranzo** [comment]
Deploying on KNI3 succeeds it fails with ipi job :/

**Comment by rlopez133** [comment]
@iranzo regarding 99-etc-chrony.conf.j2, since we are changing this, how about we change the template name to chrony.conf.j2 so that its not dependent on a number and leave the 98 pieces for the tasks?

**Comment by iranzo** [comment]
> @iranzo regarding 99-etc-chrony.conf.j2, since we are changing this, how about we change the template name to chrony.conf.j2 so that its not dependent on a number and leave the 98 pieces for the tasks?

As we need both files (one is the actual conf and the other is the yaml), I've removed the XX-etc-chronny to leave etc-chrony and get the final number when it's rendered into final destination

**Comment by rlopez133** [comment]
CI has been flaky, testing on my KNI4, will merge if success.

**Pull request merged**
