### PR TITLE
Remove pyghmi,crypto package references

### PR DESCRIPTION
**Pull request by tonyskapunk**
# Description

The RDO repository removed the rhel8/centos8 packages[0] as CentOS Stream 8 is EOL by the end of May. The role[1] has been modified to avoid the need of such requirement.

[0] https://lists.rdoproject.org/archives/list/dev@lists.rdoproject.org/thread/Q3AD6A5B3RM5ENAN6MCXICCVTQJYNLTD/
[1] https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/314

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] This change is a documentation update

## Testing

This is a change on documentation.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by tonyskapunk** [comment]
@derekhiggins I'm unsure if any other test is needed, the pending test seems to run only on approved PRs. Do you know if any other test is needed before approval? Thanks!

**Comment by derekhiggins** [comment]
/approve
/lgtm
thanks

**Pull request merged**
