### PR TITLE
Ternary

### PR DESCRIPTION
**Pull request by smalleni**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by smalleni** [comment]
Sorry riased this here instead of my fork accidentally :)

**Comment by DirectedSoul1** [comment]
No worries, just let us know what exactly is the req, we will do our best. :)

**Comment by smalleni** [comment]
We already maintain a fully automated solution based on this repo but specific to performance and scale shared labs at 
https://github.com/redhat-performance/JetSki. This PR was supposed to go there :)

**Comment by DirectedSoul1** [comment]
okie, gotcha.

**Pull request closed without merging**
