### PR TITLE
Update link naming and typo

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Fix typo and hopefully broken internal links to bmc

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Review by DirectedSoul1 — APPROVED** [review]
/lgtm

**Comment by iranzo** [comment]
Waiting for @e-minguez to validate that fixes the issue reported

**Comment by iranzo** [comment]
> /lgtm
> /approve
> /merge
> /thanks

ROFL, vendo opel corsa

**Comment by iranzo** [comment]
@johnwilkins FYI

**Pull request merged**
