### PR TITLE
fix(10_get_oc.yml): use retries on uri module instead of get_url

### LINKED ISSUE #534: RFE: Retry the get commands
This just happened to me:

```
TASK [installer : Get the ocp client tar gunzip file] **************************
Thursday 15 October 2020  06:27:45 +0000 (0:00:00.382)       0:04:44.801 ****** 

fatal: [kni1-bootstrap.example.com -> kni1-bootstrap.example.com]: FAILED! => {"changed": false, "dest": "/tmp/ansible.ae4q52o64.4.5", "elapsed": 10, "gid": 1000, "group": "kni", "mode": "0700", "msg": "Request failed: <urlopen error _ssl.c:880: The handshake operation timed out>", "owner": "kni", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 6, "state": "directory", "uid": 1000, "url": "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.4.5/openshift-client-linux-4.4.5.tar.gz"}
```

I guess a retry here won't hurt https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/installer/tasks/10_get_oc.yml#L83-L91

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Add retries on URI module instead of get_url for OC download

Closes #534

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by iranzo** [comment]
[test-ipi]

**Comment by DirectedSoul1** [comment]
I tried `4.4.5` on my Dell setup and on HPE set up, but I never experience the issue #534, but adding retries shouldn't hurt either.

**Comment by iranzo** [comment]
@rlopez133 can you give ACK? seems that IPI tests passed

**Comment by rlopez133** [comment]
Going to close based on that we believe get_url is a better choice for this.

**Pull request closed without merging**
