### PR TITLE
Attempt to tune prow

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Attempt to tune prow for label and reviewer management

Fixes # (issue)

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by slintes** [comment]
oh wow, may ask why you basically removed developers of everything in the `/features` dir as reviewers and approvers of their own code / configs?

/cc @MarSik fyi

**Comment by rlopez133** [comment]
Hi @slintes @MarSik , apologies if you felt this was in error. We honestly were just looking to cleanup the baremetal-deploy repository a bit since my understanding is your work was under: https://github.com/openshift-kni/performance-addon-operators and we were trying to get prow to better add reviewers based on the activity in the pulls coming into baremetal-deploy. @iranzo will be creating a PR to add you all back into the features section so as you mentioned you can be reviewers and approvers of your `/features` dir ( #378 )

**Comment by slintes** [comment]
>  your work was under: https://github.com/openshift-kni/performance-addon-operators 

for OCP 4.4 and later yes, but everything for 4.3 is here :slightly_smiling_face:  (even though it might not be used by anyone anymore)

**Pull request merged**
