### PR TITLE
adding pieces needed for fully disconnected

### LINKED ISSUE #261: [RFE] Handle fully disconnected installation
Provide a scenario where the playbook can handle a fully disconnected installation

### PR DESCRIPTION
**Pull request by rlopez133**
# Description

This is a WIP on getting fully disconnected installs. 

Fixes #261 #224

## Type of change

Please select the appropiate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [x] I have performed a self-review of my own code
- [x] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not being merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by johnbieren** [comment]
[test-ipi]

tags: packages

[inventory]
cert_country=dummy

**Comment by rlopez133** [comment]
> [test-ipi]
> 
> tags: packages
> 
> [variables]
> cert_country=dummy

FYI you picked the one variable that needs to be 2 characters :D

**Comment by johnbieren** [comment]
> > [test-ipi]
> > tags: packages
> > [variables]
> > cert_country=dummy
> 
> FYI you picked the one variable that needs to be 2 characters :D

heh, I didn't get it working yet anyways. Groovy + bash interaction fun. still wip

**Comment by iranzo** [comment]
~~~
TASK [node-prep : Fail when provision host no online access and registry host not creating registry (can'
t assume access)] ***                                                                                    
Wednesday 22 April 2020  10:15:19 +0000 (0:00:03.978)       0:00:08.052 *******                          
fatal: [kni3-deployhost.kni3.cloud.lab.eng.bos.redhat.com]: FAILED! => {"msg": "The conditional check 'gr
oups['registry_host'][0]|length' failed. The error was: error while evaluating conditional (groups['regis
try_host'][0]|length): 'dict object' has no attribute 'registry_host'\n\nThe error appears to be in '/hom
e/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 166, column 3, 
but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to
 be:\n\n# if prov host no access, registry host no access, require user enter an existing webserver_url\n
- name: Fail when provision host no online access and registry host not creating registry (can't assume a
ccess)\n  ^ here\n"}                                                                                     
~~~

Just patching over my repo and running with same inventory

**Comment by abays** [comment]
> ```
> TASK [node-prep : Fail when provision host no online access and registry host not creating registry (can'
> t assume access)] ***                                                                                    
> Wednesday 22 April 2020  10:15:19 +0000 (0:00:03.978)       0:00:08.052 *******                          
> fatal: [kni3-deployhost.kni3.cloud.lab.eng.bos.redhat.com]: FAILED! => {"msg": "The conditional check 'gr
> oups['registry_host'][0]|length' failed. The error was: error while evaluating conditional (groups['regis
> try_host'][0]|length): 'dict object' has no attribute 'registry_host'\n\nThe error appears to be in '/hom
> e/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 166, column 3, 
> but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to
>  be:\n\n# if prov host no access, registry host no access, require user enter an existing webserver_url\n
> - name: Fail when provision host no online access and registry host not creating registry (can't assume a
> ccess)\n  ^ here\n"}                                                                                     
> ```
> 
> Just patching over my repo and running with same inventory
> 
> Of course variable needs to be defined, but I would expect for deployment to continue working in the same way if nothing is requesting new features in my configuration?
> 
> Just relaunching it worked, so looked like a transitory failure, can we also use some other website as 'validation' of internet connectivity? and perform two tests?

I think line 175 in `roles/node-prep/tasks/10_validation.yml` needs to be changed from `groups['registry_host'][0]|length` to `groups['registry_host']|length` (and possibly even also add `'registry_host' in groups`)

**Comment by rlopez133** [comment]
> > ```
> > TASK [node-prep : Fail when provision host no online access and registry host not creating registry (can'
> > t assume access)] ***                                                                                    
> > Wednesday 22 April 2020  10:15:19 +0000 (0:00:03.978)       0:00:08.052 *******                          
> > fatal: [kni3-deployhost.kni3.cloud.lab.eng.bos.redhat.com]: FAILED! => {"msg": "The conditional check 'gr
> > oups['registry_host'][0]|length' failed. The error was: error while evaluating conditional (groups['regis
> > try_host'][0]|length): 'dict object' has no attribute 'registry_host'\n\nThe error appears to be in '/hom
> > e/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 166, column 3, 
> > but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to
> >  be:\n\n# if prov host no access, registry host no access, require user enter an existing webserver_url\n
> > - name: Fail when provision host no online access and registry host not creating registry (can't assume a
> > ccess)\n  ^ here\n"}                                                                                     
> > ```
> > 
> > 
> > Just patching over my repo and running with same inventory
> > Of course variable needs to be defined, but I would expect for deployment to continue working in the same way if nothing is requesting new features in my configuration?
> > Just relaunching it worked, so looked like a transitory failure, can we also use some other website as 'validation' of internet connectivity? and perform two tests?
> 
> I think line 175 in `roles/node-prep/tasks/10_validation.yml` needs to be changed from `groups['registry_host'][0]|length` to `groups['registry_host']|length` (and possibly even also add `'registry_host' in groups`)

@iranzo @abays - I just patched it up with abays suggestions. @iranzo give it another go?

**Comment by iranzo** [comment]
It's ongoing, I'll report once it finishes

**Comment by iranzo** [comment]
With the latest patch in master, probably the one conflicting:

~~~
TASK [node-prep : Set release_url for development envs] *************************************************
Thursday 23 April 2020  12:47:23 +0000 (0:00:00.078)       0:00:04.376 ********                          
fatal: [kni3-]: FAILED! => {"msg": "The task includes an opti
on with an undefined variable. The error was: 'webserver_url' is undefined\n\nThe error appears to be in 
'/home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 129, colum
n 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appea
rs to be:\n\n\n- name: Set release_url for development envs\n  ^ here\n"}                                
~~~

**Comment by iranzo** [comment]
> With the latest patch in master, probably the one conflicting:
> 
> ```
> TASK [node-prep : Set release_url for development envs] *************************************************
> Thursday 23 April 2020  12:47:23 +0000 (0:00:00.078)       0:00:04.376 ********                          
> fatal: [kni3-]: FAILED! => {"msg": "The task includes an opti
> on with an undefined variable. The error was: 'webserver_url' is undefined\n\nThe error appears to be in 
> '/home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 129, colum
> n 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appea
> rs to be:\n\n\n- name: Set release_url for development envs\n  ^ here\n"}                                
> ```

Retested after the rebase and install via the playbook worked with my previous settings untouched

**Comment by rlopez133** [comment]
> > With the latest patch in master, probably the one conflicting:
> > ```
> > TASK [node-prep : Set release_url for development envs] *************************************************
> > Thursday 23 April 2020  12:47:23 +0000 (0:00:00.078)       0:00:04.376 ********                          
> > fatal: [kni3-]: FAILED! => {"msg": "The task includes an opti
> > on with an undefined variable. The error was: 'webserver_url' is undefined\n\nThe error appears to be in 
> > '/home/kni/baremetal-deploy/ansible-ipi-install/roles/node-prep/tasks/10_validation.yml': line 129, colum
> > n 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appea
> > rs to be:\n\n\n- name: Set release_url for development envs\n  ^ here\n"}                                
> > ```
> 
> Retested after the rebase and install via the playbook worked with my previous settings untouched

As Edu would say, \o/

**Pull request merged**
